# C- ctr | M- meta | S- shift
# bind prefix | bind -n global (no prefix) 

set -g terminal-features "tmux-256color:RGB"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
#set -s escape-time 0
set -g set-clipboard on

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Start window numbering at 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# next/prev
bind -n M-Enter new-window
bind -n M-[ previous-window
bind -n M-] next-window

# Split panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# pane switching
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-H resize-pane -L 5
bind -n M-J resize-pane -D 5
bind -n M-K resize-pane -U 5
bind -n M-L resize-pane -R 5

bind -n M-X kill-session
bind -n M-q kill-window
bind -n M-x kill-pane

bind , command-prompt -I "#W" "rename-window '%%'"

bind r source-file ~/.config/tmux/tmux.conf \; display-message "config reloaded"

# === STYLING ===
set -g status-position top
set -g status-interval 15

set -g status-left ""
set -g status-right ""
set -g status-style "bg=default,fg=colour245"

setw -g window-status-format "#I"
setw -g window-status-current-format "#[bold][#I]"
setw -g window-status-separator " "

setw -g automatic-rename on
